# 1. Chọn base image
FROM postgres:15

# 2. Thiết lập credentials & DB name
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=secret
ENV POSTGRES_DB=mydb

# 4. Expose port (tùy chọn, để host connect)
EXPOSE 5432

